[package]
name = "ssbumpToNormal"
version = "0.1.0"
authors = ["Robert <rob5300@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
image = "0.24.5"
